export const CREATE_AMILCAR = "CREATE_AMILCAR";

export const RETRIEVE_AMILCARS = "RETRIEVE_AMILCARS";

export const UPDATE_AMILCAR = "UPDATE_AMILCAR";

export const DELETE_AMILCAR = "DELETE_AMILCAR";